FROM ghcr.io/rocker-org/verse:4.3.1
# This image uses the Rocker-Project verse RStudio image - thanks R OpenSci and Rocker!
# https://rocker-project.org/images/versioned/rstudio.html
# 
# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="CyVerse RStudio verse" \
      org.label-schema.description="Built from Rocker-Project RStudio Verse, additional depends for CyVerse K8s workbench" \
      org.label-schema.url="https://cyverse.org" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="e.g. https://github.com/cyverse-vice/rstudio-verse" \
      org.label-schema.vendor="CyVerse" \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0.0"

# Install a few dependencies for GoCommands, text editing, and monitoring instances
RUN apt update && apt install -y apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    gcc \
    glances \
    gnupg2 \
    htop \
    less \
    libfuse2 \
    lsb-release \  
    nano \
    nginx \
    nodejs \
    software-properties-common \
    supervisor \ 
    wget

# Add gomplate
ADD https://github.com/hairyhenderson/gomplate/releases/download/v3.11.5/gomplate_linux-amd64 /usr/bin/gomplate
RUN chmod a+x /usr/bin/gomplate

# provide read and write access to Rstudio users for default R library location
RUN chmod -R 777 /usr/local/lib/R/site-library

ENV PASSWORD "rstudio1"
#RUN bash /etc/cont-init.d/userconf

COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

COPY nginx.conf.tmpl /nginx.conf.tmpl
COPY rserver.conf /etc/rstudio/rserver.conf
COPY supervisor-nginx.conf /etc/supervisor/conf.d/nginx.conf
COPY supervisor-rstudio.conf /etc/supervisor/conf.d/rstudio.conf

ENV REDIRECT_URL "http://localhost/"

ARG LOCAL_USER=rstudio
ARG PRIV_CMDS='/bin/ch*,/bin/cat,/bin/gunzip,/bin/tar,/bin/mkdir,/bin/ps,/bin/mv,/bin/cp,/usr/bin/apt*,/usr/bin/pip*,/bin/yum'

RUN if [ -x /usr/bin/apt ]; then \
      apt-get update && apt-get -y install sudo && rm -rf /var/lib/apt/lists/*; \
    elif [ -x /bin/yum ]; then \
      yum -y update && yum -y install sudo && yum clean all; \
    fi
RUN echo "$LOCAL_USER	ALL=NOPASSWD: $PRIV_CMDS" >> /etc/sudoers

# Install GoCommands
# https://learning.cyverse.org/ds/gocommands/
RUN cd /usr/local/bin && \
    curl -L -o gocmd.tar.gz https://github.com/cyverse/gocommands/releases/download/v0.7.1/gocmd-v0.7.1-linux-amd64.tar.gz && \
    tar zxvf gocmd.tar.gz && rm gocmd.tar.gz

USER rstudio
# updates the PS1 prompt to say "cyverse" instead of the container name
RUN echo 'export PS1="[\u@cyverse] \w $ "' >> /home/rstudio/.bashrc

USER root

ENTRYPOINT ["/usr/local/bin/run.sh"]
